Experiment improvements
theia-ide/tsp-python-client pull request #20
Opened 2020-11-16 15:43 UTC by bhufmann

- Create an experiment from list of trace paths.
- Delete experiments also deletes traces when a certain flag is passed.

2020-12-01 20:26 UTC, bhufmann commented on tsp-cli-client
> +                    response = tsp_client.open_trace(path, path)
we should use the last segment as name otherwise the server resource path would be too long.

2020-12-01 21:36 UTC, PatrickTasse requested changes

2020-12-01 21:36 UTC, PatrickTasse commented on tsp-cli-client
> +    parser.add_argument("--paths", dest="paths", help="Also delete traces when deleting experiment", nargs="*")
The help is wrong?

2020-12-01 21:36 UTC, PatrickTasse commented on tsp-cli-client
> +                print("Provide a path for the trace using option --path")
Should it be --paths ?

2020-12-01 21:40 UTC, bhufmann commented on tsp-cli-client
> +    parser.add_argument("--paths", dest="paths", help="Also delete traces when deleting experiment", nargs="*")
true. I'll fix it.

2020-12-01 21:40 UTC, bhufmann commented on tsp-cli-client
> +                print("Provide a path for the trace using option --path")
also true. I'll fix it

2020-12-02 14:06 UTC, PatrickTasse approved these changes

2020-12-02 14:15 UTC, merged