Update README.md with correct project name
theia-ide/tsp-python-client pull request #21
Opened 2021-04-16 14:52 UTC by frobino

The name of the project was misspelled.

2021-04-16 17:10 UTC, MatthewKhouzam approved these changes

2021-04-16 17:30 UTC, bhufmann requested changes
Thanks. Could you please add **Signed-off-by: your-email-address** to the commit message

2021-08-05 19:54 UTC, bhufmann approved these changes

2021-08-06 13:46 UTC, bhufmann commented
Fixed with #22

2021-08-06 13:46 UTC, closed without merging